Repository oSoc18/OASIS, pull requests merged in 2018-07, with the labels that each got.

#25 Add sidebar and initial header
  package.json
  src/components/App.jsx
  src/components/Header.jsx
  src/components/Map.jsx
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/css/App.css
  src/css/Header.css
  src/css/Map.css
  src/css/Sidebar.css
  src/css/SidebarBuildingDetail.css
  src/css/SidebarSearchResult.css
  src/css/material-icons.css
  src/css/materialize.min.css
  src/fonts/MaterialIcons-Regular.eot
  src/fonts/MaterialIcons-Regular.ijmap
  src/fonts/MaterialIcons-Regular.svg
  src/fonts/MaterialIcons-Regular.ttf
  src/fonts/MaterialIcons-Regular.woff
  src/fonts/MaterialIcons-Regular.woff2
  src/index.html
  src/js/materialize.min.js
  webpack.config.js
Labels: Prio: High, feature

#30 Add missing image #24
  src/components/Header.jsx
  src/css/Header.css
  src/images/logo-oasis.svg
Labels: bug

#29 Setup dynamic code for sidebar
  src/components/Sidebar.jsx
  src/components/SidebarSearchResult.jsx
Labels: Type: Side bar, enhancement

#43 Building array in index, passed on to components
  src/components/App.jsx
  src/components/Sidebar.jsx
  src/index.js
Labels: Type: Side bar

#45 Made states in Sidebar
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
Labels: Type: Side bar

#47 Switch states by clicking on more details
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
Labels: Type: Side bar

#49 Showing the detail of a building
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/index.js
Labels: Type: Side bar

#50 try to show popup mouse over
  src/components/Map.jsx
  src/index.js
Labels: Type: Map

#51 Use create-react-app
  .babelrc
  .gitignore
  README.md
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  src/components/App.jsx
  src/components/Header.jsx
  src/components/Map.jsx
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/css/App.css
  src/css/vendor/leaflet.1.3.1.css
  src/css/vendor/material-icons.css
  src/css/vendor/materialize.min.css
  src/index.html
  src/index.js
  src/js/jquery-2.1.1.min.js
  src/js/materialize.js
  src/js/materialize.min.js
  src/registerServiceWorker.jsx
  src/test/App.test.jsx
  webpack.config.js
  yarn.lock
Labels: Prio: High, enhancement

#56 Setup Mobx State Manager
  config-overrides.js
  package.json
  src/components/App.jsx
  src/components/Map.jsx
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/index.js
  src/stores/BuildingStore.js
  yarn.lock
Labels: Type: Data

#58 Implemented Geolocation #57
  src/components/Map.jsx
Labels: Type: Map

#59 #20 search by name
  src/components/Header.jsx
  src/components/Map.jsx
  src/components/Sidebar.jsx
  src/stores/BuildingStore.js
Labels: Type: Search

#61 Made searching user friendly #60
  src/components/Header.jsx
  src/components/Sidebar.jsx
  src/stores/BuildingStore.js
Labels: Type: Search

#62 Feature/14 style search bar
  public/index.html
  src/components/Header.jsx
  src/components/SearchFilterContainer.jsx
  src/css/Header.css
  src/css/Sidebar.css
  src/css/vendor/materialize.min.css
Labels: Type: Search, feature

#68 #67 Bugfix wheelchair filter
  src/components/Header.jsx
  src/components/Sidebar.jsx
  src/stores/BuildingStore.js
Labels: bug

#72 Feature/14 style header bar
  src/components/Header.jsx
  src/components/SearchFilterContainer.jsx
  src/css/App.scss
  src/css/Header.scss
Labels: Type: Styling, enhancement

#73 #71 Add public service
  src/components/App.jsx
  src/components/Building.jsx
  src/components/Map.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/stores/BuildingStore.js
Labels: Type: Data

#74 Feature/13 style sidebar
  public/favicon-16x16.png
  public/index.html
  src/components/App.jsx
  src/components/Header.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/css/App.scss
  src/css/Header.scss
  src/css/Map.scss
  src/css/Sidebar.scss
  src/images/github_otocat.png
  src/images/map-marker-icon.png
Labels: Type: Styling

#78 Restyle header according to new design #76
  src/components/Header.jsx
  src/css/App.scss
  src/css/Header.scss
  src/images/github_otocat.png
  src/images/logo-github.svg
Labels: Type: Design, Type: Search, enhancement

#80 Feature/75 fallback public service
  src/components/App.jsx
  src/components/Building.jsx
  src/components/Header.jsx
  src/components/Map.jsx
  src/components/Sidebar.jsx
  src/components/SidebarBuildingDetail.jsx
  src/components/SidebarSearchResult.jsx
  src/stores/BuildingStore.js
Labels: Type: Data

#84 Bug/83 eject
  config/env.js
  config/jest/cssTransform.js
  config/jest/fileTransform.js
  config/paths.js
  config/polyfills.js
  config/webpack.config.dev.js
  config/webpack.config.prod.js
  config/webpackDevServer.config.js
  package-lock.json
  package.json
  scripts/build.js
  scripts/start.js
  scripts/test.js
  yarn.lock
Labels: Prio: High, bug
